### PR TITLE
Read handles from characteristics and services for linux platform

### PR DESCRIPTION
**Pull request by janoelker**
As the topic sais, I changed the linux part of the system, to make it able to read the handle for a characteristic or service. These values are needed in future use for me, so I would like to hear your opinion on this commit. 

Also is it correct to return the startHandle or is a combination of the startHandle and endHandle needed?

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@Steckdoserich thanks for submitting this PR!

I'm not too keen on promoting the use of handles. However, I am planning on introducing an ```id``` field for services, characteristics, and descriptors to resolve #175. The id will most likely be mapped to the service start handle, and characteristic/descriptor handle for both OS X and Linux.

**Comment by tal** [comment]
@sandeepmistry I'm actually hoping to have handle available for debugging purposes. I know the handle based on sniffing traffic on a device and I'm trying to be able to explore the interface based on that. So having it accessible would be very useful.

**Comment by rzr** [comment]
Please forward change to downstream fork:
#923

**Comment by rzr** [comment]
Relate-to: https://github.com/noble/noble/issues/923#issuecomment-687851954

**Pull request closed without merging**
